config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root               'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
<% provide(:title, "About") %>
<h1>About</h1>
<p>This sample web app implements basic website features such as user registration,
authentication, email verification, and password reset functionality. It also provides
for admin privileges, allowing the admin to see a paginated list of users and the ability
to delete user accounts from the site.</p>

<p>Additional features are in development.</p>

<p>This site was created using Ruby on Rails 4.2, Minitest for TDD, and Bootstrap for
Responsive layouts.</p>

<p>The sourcecode for this project can be found at 
<a href="https://bitbucket.org/cdpatton/sample_app">Bitbucket</a>.</p>
    </div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  You can find Charles Patton on <a href="www.linkedin.com/in/charles-patton-23a70a126">LinkedIn</a>, 
  <a href="https://bitbucket.org/cdpatton/">Bitbucket</a>, 
  and <a href="https://github.com/winterdharma/">Github</a>.
</p>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Fill in later.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <% if logged_in? %>
    <h2>Welcome back, <%= @user.name %>!</h2>
    
  
  <% else %>
    <h1>Welcome to the Task List <br/>Sample App</h1>
  
    <h2>
      Get organized today.
    </h2>
  
    <h3><%= link_to "Login", login_path, class: "btn btn-lg btn-primary" %>
    or
    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %></h3><h3>now!</h3>
  <% end %>
</div>

<%= link_to image_tag("rails-logo.svg", alt: "Rails logo", width: "220", height: "78"), 'http://rubyonrails.org/' %>