config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root               'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A Ruby on Rails Sample App<br/>by Charles Patton</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  
  <div class="container nav-contain">
    <div class="navbar-header">
      <button class="navbar-toggler pull-right visible-xs" type="button" data-toggle="collapse" 
        data-target=".navbar-collapse">
        <span class="glyphicon glyphicon-menu-hamburger"></span>
      </button>
      <%= link_to "sample app", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    
    <div class="collapse navbar-collapse navbar-right">
      
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to "Home", root_path %></li>
        
      
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-item active" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item active"><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
    <!-- [if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<%= render 'layouts/shim' %>
  </head>
  <body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>